### PR TITLE
Implement legacy escaping of invalid UTF-8

### PR DESCRIPTION
**Pull request by dsnet**

### CODE REVIEW

**Comment by dsnet** [comment]
I have no idea why, but someone went through the trouble of codifying this behavior in a v1 test.

**Comment by dsnet** [comment]
Found the culprit: https://golang.org/cl/11138045
😸

**Review by johanbrandhorst — APPROVED** [review]
Is `r` Robert Griesemer? This really aged like milk eh

**Comment by dsnet** [comment]
Rob Pike.

**Pull request merged**
