### PR TITLE
Adjust single-line formatting behavior

### PR DESCRIPTION
**Pull request by dsnet**
Changes made:

* Further separate the behavior of SpaceAfterColon and SpaceAfterComma from Multiline. That is, use of Multiline does not affect the behavior of SpaceAfterColon or SpaceAfterComma unless it has not been set. For example, specifying (SpaceAfterColon(false), Multiline(true)) should avoid the space after the colon even if we expect this combination of options to be seldom used.

* Exclude whitespace formatting flags from DefaultOptionsV1 since v1 has API support for both single-line and multi-line output, so setting (or clearing) them cannot be classified as v1 behavior. Similarly, exclude whitespace formatting flags from DefaultOptionsV2.

* Simplify the TestMarshal cases.

* Add explicit TestEncoder cases to exercise all Encoder.WriteValue code paths.

### CODE REVIEW

**Comment by dsnet** [comment]
\cc @veqryn

**Comment by mvdan** [comment]
Thanks, done.

**Comment by mvdan** [comment]
Err, I meant to merge https://github.com/go-json-experiment/json/pull/25, but this one also LGTM, so hopefully that's not a problem :sweat_smile:

**Comment by dsnet** [comment]
No worries, it was done.

**Pull request merged**
